# Chapter 2: Coding our First Neurons


## A Layer of Neurons
Each neuron has a set is weights (1 for each input) and a bias. 
Each output of neuron is calculated like so:

`output=sum(inputs*weights+bias)`

The below example shows 3 neurons with 4 different inputs (thus 4 different values for each set of weights).

In [1]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.7, -0.5, 1]
weights2 = [0.1, 0.8, 0.5, 1]
weights3 = [0.6, 0.3, -0.2, 4]

bias1 = 1
bias2 = 3
bias3 = 0.5

outputs = [
    # Neuron 1:
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,

    # Neuron 2:
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,

    # Neuron 3:
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3,
]

print(outputs)

[3.5999999999999996, 8.7, 11.1]


The above will is a lot of work and will not scale well for larger inputs. Below is the same outcome, but setup in a way that will allow for more inputs and neurons without needing to re-write the core logic.

In [10]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.7, -0.5, 1],
            [0.1, 0.8, 0.5, 1],
            [0.6, 0.3, -0.2, 4]]

biases = [1, 3, 0.5]

layer_outputs = []
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight, in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)

[3.5999999999999996, 8.7, 11.1]


## Tensors, Arrays, and Vectors

Tensors are not arrays exactly, but can be represented with arrays. 

In order for a list to be an array, it must be **homologous**. For a list of lists to be homologous, this means each list in the lists has an identical length.

To determine the shape of an array, you look at each dimension.

For example:

```#!python
lolol = [
         [[1, 2, 3, 4],[1, 2, 3, 4]],
         [[1, 2, 3, 4],[1, 2, 3, 4]], 
         [[1, 2, 3, 4],[1, 2, 3, 4]]
        ]
```

In the above list, there are 3 lists, with 2 lists inside. Then there are 4 numbers inside each of the 2 lists.

This makes the shape of the array: `(3, 2, 4)`
This is a 3 dimensional array which is why there are 3 different numbers, `(3, 2, 4)`, in the shape.

        
        


## Dot Product and Vector Addition

When multiplying vectors, you either perform a dot product or a cross product. A cross product results in a vector while a dot product results in a scalar (a single value/number).

Below is the dot product represented in Python:

In [20]:
a = [1, 2, 3]
b = [2, 3, 4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)

20


## A Single Neuron with NumPy

NumPy (A Python Library) contains a method to perform the dot product:

In [21]:
import numpy as np

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias

print(outputs)

4.8


## A Layer of Neurons with NumPy

In this example, we perform the dot product first as one operation on all neurons and inputs and add the bias in the next operation.

This is both a simplification and an optimization giving us simpler and faster code. 

In [22]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases

print(layer_outputs)

[4.8   1.21  2.385]


## A Batch of Data

To train, neural networks tend to receive data in batches.

So far, we have been using examples of input data that can be considered a sample (observation or feature set instance). Each number in the list is a feature observation datum that form a feature set instance.

NN will often take in many samples at a time because it is faster to train this way and it helps with generalization during training.

Generalization during training will help with avoiding overfitting.

## Matrix Product

The matrix product is where we perform the dot products of all rows from the first matrix and the columns of the 2nd matrix.

This operation requires that the size of the second dimension of the left matrix must match the size of the first dimension of the right matrix. 

## Transposition for the Matrix Product

ab^t represents the dot product of vectors a and b.

Transposition simply modifies a matrix in a way that its rows become columns and columns become rows.

A **row vector** is a matrix with a number of rows equals 1 and the columns equal n (any size).

`a = [a1, a2, a3, ...]`

With NumPy we would define it as `np.array([[1, 2, 3]])`.

or

```
a = [1, 2, 3]
np.array([a])
```

We encase `a` into brackets before converting to an array.

A **column vector** is a matrix where the second dimension's size (columns) equal 1. 

This can be created with numpy, but requires transposition to turn the rows into columns and columns into rows. 

b = [2, 3, 4]
b^T = [2, 3, 4]^T = 

[2] <br>
[3] <br>
[4] <br>



In [23]:
import numpy as np

a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

print(np.dot(a, b))

[[20]]


## A Layer of Neurons & Batch of Data w/ NumPy



In [25]:

inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

# This will need to get transposed for the Matrix product.
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
